### ISSUE TITLE
Freeplay function is weird

### ISSUE THREAD

**Issue by JayFoxRox** [JayFoxRox/VPinMAME_SPA#1]
* No arguments here: https://github.com/JayFoxRox/VPinMAME_SPA/blob/a78c5f39039f2438a162a9370f91c9bfd29025a2/src/wpc/sternpba.c#L74
* No arguments here: https://github.com/JayFoxRox/VPinMAME_SPA/blob/a78c5f39039f2438a162a9370f91c9bfd29025a2/src/wpc/sternpba.c#L382
* No arguments here: https://github.com/JayFoxRox/VPinMAME_SPA/blob/a78c5f39039f2438a162a9370f91c9bfd29025a2/src/wpc/sternpba.c#L459
* 1 argument here: https://github.com/JayFoxRox/VPinMAME_SPA/blob/a78c5f39039f2438a162a9370f91c9bfd29025a2/src/wpc/sternpba.c#L525

How does this even compile?!

**Comment by djrobx** [comment]
It compiles although it probably shouldn't.   :)  MSVC says:

1>c:\source\vpinmame_spa\src\wpc\sternpba.c(525): warning C4087: 'stern_set_free_play_fn': declared with 'void' parameter list

I originally "guessed" that set_free_play had a 1/0 parameter, leading to folks being unable to turn off free play.   I later fixed this but missed updating one of them, obviously.  :)
